# Generated by Django 5.2.15 on 2026-07-01 01:02

from django.db import migrations, models


def backfill_positions(apps, schema_editor):
    """Seed the manual order from the existing default (smart) ordering."""
    Task = apps.get_model("tasks", "Task")
    ordered = Task.objects.order_by(
        "completed", "-priority", "due_date", "-created_at"
    )
    for index, task in enumerate(ordered):
        task.position = index
    Task.objects.bulk_update(ordered, ["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_created_at_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_positions, migrations.RunPython.noop),
    ]
